# Generated by Django 5.2.6 on 2025-09-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('product_type', models.CharField(help_text='Product Type (e.g., 109LT)', max_length=20)),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique identifier', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('available_stock_rolls', models.IntegerField(default=0, help_text='Available stock in rolls')),
                ('reserved_stock', models.IntegerField(default=0, help_text='Stock reserved for orders')),
                ('minimum_stock_level', models.IntegerField(default=0, help_text='Minimum stock threshold')),
                ('maximum_stock_level', models.IntegerField(default=100, help_text='Maximum stock capacity')),
                ('warehouse_location', models.CharField(blank=True, help_text='Physical location in warehouse', max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, help_text='Primary supplier', max_length=100, null=True)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Supplier lead time in days')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit', max_digits=10)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Last purchase price', max_digits=10)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this stock item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_stock_update', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(db_column='color_code', on_delete=django.db.models.deletion.CASCADE, to='colors.color')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'stock',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for IN, negative for OUT')),
                ('old_stock_level', models.IntegerField()),
                ('new_stock_level', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, help_text='Order number, transfer ID, etc.', max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, help_text='User who made this movement', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['product_type'], name='stock_product_b549c3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['color'], name='stock_color_c_c35a88_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['is_active'], name='stock_is_acti_c8460a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['available_stock_rolls'], name='stock_availab_95624e_idx'),
        ),
    ]
