# Generated by Django 5.2.6 on 2026-06-11 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_deleted_at_brand_is_deleted_and_more'),
        ('stock', '0002_stockitem_deleted_at_stockitem_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='primary_location',
            field=models.ForeignKey(blank=True, help_text='Primary location where the stock item is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_stock_items', to='products.location'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(default=None, help_text='Linked Product (required)', on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='secondary_location',
            field=models.ForeignKey(blank=True, help_text='Secondary/backup location for the stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_stock_items', to='products.location'),
        ),
    ]
