# Generated by Django 5.2.6 on 2026-06-12 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def ensure_locations_table(apps, schema_editor):
    Location = apps.get_model('products', 'Location')
    if Location._meta.db_table in schema_editor.connection.introspection.table_names():
        return
    schema_editor.create_model(Location)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_available_stock_rolls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(ensure_locations_table, migrations.RunPython.noop),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(max_length=500)),
                ('supplier', models.CharField(max_length=100)),
                ('batch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_meterage', models.PositiveIntegerField(default=0)),
                ('roll_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the record was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches_created', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_batches', to='stock.stockitem')),
            ],
            options={
                'db_table': 'stock_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBatchRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.PositiveIntegerField()),
                ('meterage', models.PositiveIntegerField()),
                ('label_generated', models.BooleanField(default=False)),
                ('label_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='stock.stockbatch')),
                ('label_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_roll_labels_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_batch_rolls',
                'ordering': ['roll_number'],
            },
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_id'], name='stock_batch_batch_i_2d7dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['sku'], name='stock_batch_sku_b89236_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['batch_date'], name='stock_batch_batch_d_b17258_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['supplier'], name='stock_batch_supplie_8f5306_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatchroll',
            constraint=models.UniqueConstraint(fields=('batch', 'roll_number'), name='unique_roll_per_stock_batch'),
        ),
    ]
