# Generated by Django 5.2.6 on 2025-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_code', models.CharField(help_text='Color abbreviation code (e.g., ABRN)', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('color_name', models.CharField(help_text='Full color name (e.g., Auburn Brown)', max_length=100)),
                ('secondary_code', models.CharField(blank=True, help_text='Secondary color code if applicable', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'colors',
                'ordering': ['color_code'],
            },
        ),
    ]
