# Generated by Django 5.2.6 on 2025-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the record was deleted', null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
