# Generated by Django 5.2.6 on 2026-08-11 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_clear_derived_sample_summary_personalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=30, unique=True)),
                ('batch_number', models.PositiveSmallIntegerField(choices=[(1, 'Batch 1'), (2, 'Batch 2'), (3, 'Batch 3'), (4, 'Batch 4'), (5, 'Batch 5')])),
                ('batch_date', models.DateField(default=django.utils.timezone.localdate)),
                ('filters_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_batches_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_batches_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Batch',
                'verbose_name_plural': 'Order Batches',
                'db_table': 'order_batches',
                'ordering': ['-batch_date', 'batch_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderBatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='orders.orderbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_links', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Batch Order',
                'verbose_name_plural': 'Order Batch Orders',
                'db_table': 'order_batch_orders',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['batch_date', 'batch_number'], name='order_batch_batch_d_6718f1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['batch_name'], name='order_batch_batch_n_ee01fc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbatch',
            index=models.Index(fields=['is_deleted'], name='order_batch_is_dele_48aa0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderbatch',
            constraint=models.UniqueConstraint(fields=('batch_date', 'batch_number'), name='unique_order_batch_date_number'),
        ),
        migrations.AddIndex(
            model_name='orderbatchorder',
            index=models.Index(fields=['batch', 'order'], name='order_batch_batch_i_ab520f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbatchorder',
            index=models.Index(fields=['order'], name='order_batch_order_i_9959ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderbatchorder',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='unique_order_in_batch'),
        ),
    ]
