# Generated by Django 5.2.6 on 2025-09-25 10:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('vs_parent_id', models.PositiveIntegerField(help_text='VS Parent ID from Excel')),
                ('vs_child_id', models.PositiveIntegerField(help_text='VS Child ID from Excel', primary_key=True, serialize=False, unique=True)),
                ('parent_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('child_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_product_title', models.CharField(max_length=500)),
                ('child_product_title', models.CharField(max_length=500)),
                ('product_subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('product_summary', models.TextField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('attribute_length', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_colour', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_top_sizes', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_dress_sizes', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_print', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_width', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_size', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_choose_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_design', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_gift_card_value', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute_colours_pf', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_colours', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_matching_lycra_mesh', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_material', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_materials', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_print_texture', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_quantity_box', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_trimmings', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('available_now', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('deposit_price_inc_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rrp_price_inc_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cost_price_inc_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('price_break_1_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_break_1_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_break_1_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_break_2_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_break_2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_break_2_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_break_3_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_break_3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_break_3_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_purchase_quantity', models.PositiveIntegerField(default=0)),
                ('min_purchase_quantity', models.PositiveIntegerField(default=1)),
                ('minimum_age', models.PositiveIntegerField(default=0)),
                ('pick_location', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_message', models.CharField(blank=True, max_length=200, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('child_active', models.BooleanField(default=True)),
                ('parent_active', models.BooleanField(default=True)),
                ('archive_delete', models.BooleanField(default=False)),
                ('archive_redirect_url', models.URLField(blank=True, null=True)),
                ('parent_product_url', models.URLField(blank=True, null=True)),
                ('child_product_url', models.URLField(blank=True, null=True)),
                ('parent_product_images', models.URLField(blank=True, null=True)),
                ('child_product_images', models.URLField(blank=True, null=True)),
                ('display_on_sale_page', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('trade_only_product', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('categories', models.ManyToManyField(blank=True, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['vs_child_id'],
                'indexes': [models.Index(fields=['vs_parent_id'], name='products_vs_pare_87c09e_idx'), models.Index(fields=['parent_reference'], name='products_parent__a3af2d_idx'), models.Index(fields=['child_reference'], name='products_child_r_965bc5_idx'), models.Index(fields=['child_active'], name='products_child_a_d6bbf7_idx'), models.Index(fields=['parent_active'], name='products_parent__c49659_idx')],
            },
        ),
    ]
